python_web/Tweeter/Tweeter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.urls import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home),
    path('tweet/', include('tweet.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_web/Tweeter/tweet/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.tweet_list, name='tweet_list'),
    path('create/', views.tweet_create, name='tweet_create'),
    path('<int:tweet_id>/edit/', views.tweet_edit, name='tweet_edit'),
    path('<int:tweet_id>/delete/', views.tweet_delete, name='tweet_delete'),

    path('register/', views.register , name='register'),
]

python_web/Tweeter/tweet/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=240)
    image = models.ImageField(upload_to='images/', blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} - {self.text[:15]}'

python_web/Tweeter/tweet/forms.py
from django import forms
from .models import Tweet
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['text', 'image']      


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

python_web/Tweeter/Tweeter/views.py
from django.shortcuts import render


def Home(request):
    return render(request, 'home.html')

python_web/Tweeter/tweet/views.py
from django.shortcuts import render
from .models import Tweet
from .forms import TweetForm, UserRegistrationForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
# Create your views here.

def index(request):
    return render(request, 'index.html')


def tweet_list(request):
    tweets = Tweet.objects.all().order_by('-created_at')
    return render(request, 'tweet_list.html', {'tweets': tweets})

@login_required
def tweet_create(request):
    if request.method == "POST":
      form = TweetForm(request.POST, request.FILES)
      if form.is_valid():
         tweet = form.save(commit=False)
         tweet.user = request.user
         tweet.save()
         return redirect('tweet_list')
    else:
       form = TweetForm()
    return render(request, 'tweet_from.html', {'form': form, 'is_edit': False})

@login_required
def tweet_edit(request, tweet_id):
   tweet = get_object_or_404(Tweet, pk=tweet_id, user = request.user)
   if request.method == "POST":
     form = TweetForm(request.POST, request.FILES, instance=tweet)
     if form.is_valid():
        tweet = form.save(commit=False)
        tweet.user = request.user
        tweet.save()
        return redirect('tweet_list')
   else:
      form = TweetForm(instance=tweet)
   return render(request, 'tweet_from.html', {'form': form, 'is_edit': True})   

@login_required
def tweet_delete(request, tweet_id):
   tweet = get_object_or_404(Tweet, pk=tweet_id, user = request.user)
   if request.method == "POST":
      tweet.delete()
      return redirect('tweet_list')
   return render(request, 'tweet_confirm_delete.html', {'tweet': tweet})
  

def register(request):
   form_submitted = False
   if request.method == 'POST':
    form = UserRegistrationForm(request.POST)
    form_submitted = True
    if form.is_valid():
       user = form.save(commit=False)
       user.set_password(form.cleaned_data['password1'])
       user.save()
       login(request, user)
       return redirect('tweet_list')
   else:
      form = UserRegistrationForm()
   return render(request, 'registration/register.html', {'form': form, 'form_submitted': form_submitted})

python_web/Tweeter/templates/home.html
{% extends "layout.html" %} {% block title %} Main Index Page {% endblock %} 


{% block content %}
<section id="home">
  <div class="container">
    <div class="row text-center py-5">
      <div class="col-md-12">
        <h1>Wellcome to Django's Tweeter</h1>
      </div>
    </div>
    <div class="row mb-3 py-5">
      <div class="col-md-4">
        <div class="card">
          <img src="..." class="card-img-top" alt="..." />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title and make up the
              bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card">
          <img src="..." class="card-img-top" alt="..." />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title and make up the
              bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card">
          <img src="..." class="card-img-top" alt="..." />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title and make up the
              bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
    <div class="row pb-5">
      <div class="col-md-4">
        <div class="card">
          <img src="..." class="card-img-top" alt="..." />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title and make up the
              bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card">
          <img src="..." class="card-img-top" alt="..." />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title and make up the
              bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card">
          <img src="..." class="card-img-top" alt="..." />
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
              Some quick example text to build on the card title and make up the
              bulk of the card's content.
            </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

python_web/Tweeter/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


    {% comment %} <link rel="stylesheet" href="{% static "css/style.css" %}"> {% endcomment %}
    <script src="{% static "js/error_handling.js" %}"></script>
    <title>{% block title %} Page Title {% endblock %}</title>
  </head>
  <body class="dark">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Services
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Django Apps</a></li>
                  <li><a class="dropdown-item" href="#">React js</a></li>
                  <li><a class="dropdown-item" href="#">Laravel</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "tweet_create" %}">Create Tweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "tweet_list" %}">All Tweets</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Contact</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>

            
            {% if user.is_authenticated %}
              <form method="post" action="{% url "logout" %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mx-2">Logout</button>
              </form>
             
            {% else %}
            <a href="{% url "register" %}" class="btn btn-primary mx-2">Register</a>
            <a href="{% url "login" %}" class="btn btn-success mx-2">Login</a>
            {% endif %}
            
           

          </div>
        </div>
      </nav>

    {% block content %}
    <div class="wrapper">
      <h1>Site Layout Page</h1>
    </div>
    {% endblock %}

    <footer class="footer bg-danger">
      <div class="container">
        <div class="row">
          <div
            class="col-sm-6 col-md-4 mt-4 col-lg-3 text-center text-sm-start"
          >
            <div class="information">
              <h6 class="footer-heading text-uppercase text-white fw-bold">
                Information
              </h6>
              <ul class="list-unstyled footer-link mt-4">
                <li class="mb-1">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >Events</a
                  >
                </li>
                <li class="mb-1">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >Our Team</a
                  >
                </li>
                <li class="mb-1">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >Upcoming Sale</a
                  >
                </li>
                <li class="">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >New Launches</a
                  >
                </li>
              </ul>
            </div>
          </div>
          <div
            class="col-sm-6 col-md-4 mt-4 col-lg-3 text-center text-sm-start"
          >
            <div class="resources">
              <h6 class="footer-heading text-uppercase text-white fw-bold">
                Resources
              </h6>
              <ul class="list-unstyled footer-link mt-4">
                <li class="mb-1">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >API</a
                  >
                </li>
                <li class="mb-1">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >Website Tutorials</a
                  >
                </li>
                <li class="mb-1">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >Third Party</a
                  >
                </li>
                <li class="">
                  <a
                    href="#"
                    class="text-white text-decoration-none fw-semibold"
                    >Video Lectures</a
                  >
                </li>
              </ul>
            </div>
          </div>
          <div
            class="col-sm-6 col-md-4 mt-4 col-lg-2 text-center text-sm-start"
          >
            <div class="social">
              <h6 class="footer-heading text-uppercase text-white fw-bold">
                Social
              </h6>
              <ul class="list-inline my-4">
                <li class="list-inline-item">
                  <a href="#" class="text-white btn-sm btn btn-primary mb-2"
                    ><i class="bi bi-facebook"></i
                  ></a>
                </li>
                <li class="list-inline-item">
                  <a href="#" class="text-danger btn-sm btn btn-light mb-2"
                    ><i class="bi bi-instagram"></i
                  ></a>
                </li>
                <li class="list-inline-item">
                  <a href="#" class="text-white btn-sm btn btn-primary mb-2"
                    ><i class="bi bi-twitter"></i
                  ></a>
                </li>
                <li class="list-inline-item">
                  <a href="#" class="text-white btn-sm btn btn-success mb-2"
                    ><i class="bi bi-whatsapp"></i
                  ></a>
                </li>
              </ul>
            </div>
          </div>
          <div
            class="col-sm-6 col-md-6 mt-4 col-lg-4 text-center text-sm-start"
          >
            <div class="contact">
              <h6 class="footer-heading text-uppercase text-white fw-bold">
                Contact Us
              </h6>
              <address class="mt-4 m-0 text-white mb-1">
                <i class="bi bi-pin-map fw-semibold"></i> New South Block ,
                Phase 8B , 160055
              </address>
              <a
                href="#"
                class="text-white mb-1 text-decoration-none d-block fw-semibold"
                ><i class="bi bi-telephone"></i> 909090XXXX</a
              >
              <a
                href="#"
                class="text-white mb-1 text-decoration-none d-block fw-semibold"
                ><i class="bi bi-envelope"></i> xyzdemomail@gmail.com</a
              >
              <a href="#" class="text-white text-decoration-none fw-semibold"
                ><i class="bi bi-skype"></i> xyzdemomail</a
              >
            </div>
          </div>
        </div>
      </div>
      <div class="text-center bg-dark text-white mt-4 p-1">
        <p class="mb-0 fw-bold">2023 © Gaurav Rana, All Rights Reserved</p>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

python_web/Tweeter/tweet/templates/index.html
{% extends "layout.html" %}


{% block title %}
 Tweet | Page
{% endblock  %}


{% block content %}
<h1>Hello Tweeter's | Mini App</h1>
{% endblock  %}

python_web/Tweeter/tweet/templates/tweet_confirm_delete.html
{% extends "layout.html" %}

{% block title %}
Delete Tweet | Page
{% endblock  %}


{% block content %}
 
<div class="container">
    <div class="row py-5 text-center">
        <h1 class=" mt-4">Are you sure you want to delete this Tweet </h1>
            <form method="post" class="form">
                {% csrf_token %}
              
                <button class="btn btn-danger mx-2">Delete</button>
                <a href="{% url 'tweet_list'%}" class="btn btn-success">Cancel</a>
            </form>
    </div>
</div>


{% endblock  %}

python_web/Tweeter/tweet/templates/tweet_from.html
{% extends "layout.html" %} {% block title %} add Tweet | Page {% endblock %} 


{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center mt-4">Welcome to Tweeter's Mini Tweet</h1>
      <h2>
        {% if form.instance.pk %} Edit Tweet {% else %} Create Tweet {% endif %}

        <form method="post" enctype="multipart/form-data" class="form" id="registration-form">
            {% csrf_token %}

            <div class="form-group mb-3">
                <label for="id_text" class="mb-2">Text</label>
                <textarea
                    name="text"
                    id="id_text"
                    class="form-control"
                    rows="5"
                >{{ form.text.value|default_if_none:"" }}</textarea>
                {% if form.text.errors %}
                <div class="text-danger">{{ form.text.errors.as_text }}</div>
                {% endif %}
            </div>
            <div class="form-group mb-3">
                <label for="id_image" class="mb-2">Image</label>
                <input
                    type="file"
                    name="image"
                    id="id_image"
                    class="form-control"
                />
                {% if form.instance.image %}
                    <div class="mb-3">
                        <img src="{{ form.instance.image.url }}" alt="Current image" class="img-fluid">
                    </div>
                {% endif %}
                {% if form.image.errors %}
                <div class="text-danger">{{ form.image.errors.as_text }}</div>
                {% endif %}
            </div>
        
            <button class="btn btn-warning" type="submit">
                {% if is_edit %}Update Tweet{% else %}Tweet Now{% endif %}
            </button>
            <a href="{% url 'tweet_list' %}" class="btn btn-secondary">Back to Home</a>
        </form>
        
      </h2>
    </div>
  </div>
</div>

{% endblock %}

python_web/Tweeter/tweet/templates/tweet_list.html
{% extends "layout.html" %}

{% block title %}
tweet_list | Page
{% endblock  %}


{% block content %}
 
    <h1 class="text-center mt-4">
        Welcome to Tweeter's Mini Tweet
    </h1>
    <div class="container">
        <a href="{% url "tweet_create" %}" class="btn btn-primary mb-4">Create a Tweet</a>
        <div class="row">
            
            {% for tweet in tweets  %}
            <div class="col-md-4 py-5">
                <div class="card">
                   <img src="{{tweet.image.url}}" class="card-img-top" alt="..." />
                    <div class="card-body">
                        <h5 class="card-title">{{tweet.user.username}}</h5>
                        <p class="card-text">
                        {{tweet.text}}
                        </p>
                        {% if tweet.user == user %}
                        <a href="{% url 'tweet_edit' tweet.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'tweet_delete' tweet.id %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>






{% endblock  %}